### ISSUE TITLE
media queries make it queasy

### ISSUE THREAD

**Issue by lingo** [nicooprat/Css2Less#7]
This:

``` css
@media screen and (max-width: 1000px) {
    #hello {
        color: blue;
    }

    #hello #buddy {
        background: red;
    }
}
```

Generated this, which made me queasy :)

``` css
@media {
    screen {
        and {
            (max-width: {
                1000px) {
                    #hello;
                }
            }
        }
    }
}
color: {
    #FFF; {
        #hello #buddy;
    }
}
```
